# Generated by Django 5.2.7 on 2025-10-29 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_administrador_empleado_prestamo_pago'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleado',
            name='empresa',
            field=models.CharField(default='', max_length=100),
        ),
    ]
