# Generated by Django 5.2.7 on 2025-10-29 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_empleado_empresa'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pago',
            name='saldo_despues_pago',
        ),
    ]
