# Generated by Django 5.2.7 on 2025-11-10 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_pago_saldo_despues_pago'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleado',
            name='devengado',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='empleado',
            name='fecha_corte',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='empleado',
            name='fecha_ingreso',
            field=models.DateField(blank=True, null=True),
        ),
    ]
