# Generated by Django 5.2.7 on 2025-11-10 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_empleado_acumulado_empleado_tiempo_dias_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleado',
            name='acumulado_ps',
            field=models.FloatField(default=0),
        ),
    ]
